on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm]
        exclude: 
          - goos: darwin
            goarch: arm
            
    steps:
      - uses: actions/checkout@v2
      - name: Set RELEASE_VERSION env
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
      - uses: wangyoucao577/go-release-action@master
        env:
          CGO_ENABLED: 0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          md5sum: false
          extra_files: README.md
          ldflags: -w -s
